### ISSUE TITLE
Won't get past 'Remove "*APPNAME*" ' Pop-Up. 

### ISSUE THREAD

**Issue by AdamFRC** [d4rken/gplay-batchtool#4]
App is able to press the X to the right of the listed app, but once the pop-up appears it does not click the "Remove" button. Does not freeze, as I can manually click "Remove" for each app.

**Comment by Hypfer** [comment]
Can confirm :(

**Comment by Hypfer** [comment]
https://github.com/d4rken/gplay-batchtool/blob/73575242fbbc2e3faee3051e60d68909814040be/app/src/main/java/eu/darken/gplaybatchtool/main/core/ScanService.java#L196

The confirm button is now labelled "Remove" instead of "Ok" which is why this is currently broken. (i think)

**Comment by d4rken** [comment]
Sounds plausible @Hypfer , if you can confirm it, can you create a pull request?

**Comment by d4rken** [comment]
Fixed in [v0.6](https://github.com/d4rken/gplay-batchtool/releases/tag/v0.6). :+1:
