### ISSUE TITLE
Not installing V 0.6

### ISSUE THREAD

**Issue by Sczar** [d4rken/gplay-batchtool#6]
Keep saying APK is invalid. Android 11

**Comment by d4rken** [comment]
Try again, uploaded a signed build.
Thought the previous v0.5 was also a debug signed one and it worked :thinking: .

**Comment by Ipherc** [comment]
> Try again, uploaded a signed build.
> Thought the previous v0.5 was also a debug signed one and it worked :thinking: .

Confirm. It works. Thank you
